"""add swipe history

Revision ID: 99c9bc980e1c
Revises: be44c6f0b6ef
Create Date: 2026-10-02 01:19:13.183199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c9bc980e1c'
down_revision = 'be44c6f0b6ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swipe_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('target_user_id', sa.String(length=100), nullable=False),
    sa.Column('swipe_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_user_id', 'swipe_date', name='uq_daily_swipe_user_target')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swipe_histories')
    # ### end Alembic commands ###
