"""add gomoku tables

Revision ID: ec9a50ea4acd
Revises: d23372b9f501
Create Date: 2026-09-26 05:40:01.300678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9a50ea4acd'
down_revision = 'd23372b9f501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gomoku_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('player1_id', sa.String(length=100), nullable=False),
    sa.Column('player2_id', sa.String(length=100), nullable=True),
    sa.Column('black_player_id', sa.String(length=100), nullable=True),
    sa.Column('white_player_id', sa.String(length=100), nullable=True),
    sa.Column('turn', sa.String(length=10), nullable=False),
    sa.Column('board', sa.JSON(), nullable=False),
    sa.Column('winner_id', sa.String(length=100), nullable=True),
    sa.Column('last_move_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['black_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['white_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gomoku_rooms')
    # ### end Alembic commands ###
